spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tokyo-olympics-management-db?useSSL=false
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
